version: '3'

services:
  # Service PHP + Apache
  web:
    image: php:apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"

  # Service MySQL
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  # Service PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db